routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('mailbox', 'Mailboxes');
Route::resource('rules', 'RulesController');
Route::get('/api/check/rule', 'RulesController@sync');
Route::resource('jobs', 'CronJobController');

app/Mailbox.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mailbox extends Model
{
    /**
     * Get all Rules.
     */
    public function Rules()
    {
        return $this->hasMany('App\Rules','mailbox','id');
    }
    public function delete(){
        $this->Rules()->delete();
        return parent::delete();
    }
}

resources/views/mailbox/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <a href="{{route('mailbox.index')}}" class="btn btn-primary btn-sm float-right">Back to Mailboxes</a>
    <h2>Add Mailbox</h2>
    <form action="{{route('mailbox.store')}}" method="post" class="form row">
        @csrf
        <div class="form-group col-sm-12 col-md-5">
            <label for="hostname">IMAP Hostname</label>
            <input type="text" class="form-control" name="hostname" id="hostname" value="{{old('hostname')}}">
        </div>
        <div class="form-group col-sm-12 col-md-4">
            <label for="port">IMAP Port</label>
            <input type="number" class="form-control" name="port" id="port" value="{{old('port')}}">
        </div>
        <div class="form-group col-sm-12 col-md-3">
            <label for="type">Protocol</label>
            <select class="form-control" name="type" id="type">
                <option @if(old('type') == "ssl") selected @endif value="ssl">SSL</option>
                <option @if(old('type') == "tls") selected @endif value="tls">TLS</option>
                <option @if(old('type') == "none") selected @endif value="none">None</option>
            </select>
        </div>
        <div class="form-group col-sm-12 col-md-6">
            <label for="username">IMAP Username</label>
            <input type="text" class="form-control" name="username" id="username" value="{{old('username')}}">
        </div>
        <div class="form-group col-sm-12 col-md-6">
            <label for="password">IMAP Password</label>
            <input type="password" class="form-control" name="password" id="password" value="{{old('password')}}">
        </div>
        <div class="form-group col-sm-12 col-md-6">
            <button type="submit" class="btn btn-submit">Save and Verify</button>
        </div>
    </form>
</div>
@endsection

resources/views/mailbox/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <a href="{{route('mailbox.create')}}" class="btn btn-success float-right">New Mailbox</a>
    <h2>Mailboxes</h2>
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th>Mailbox</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody class="table-bordered table-hover">
            @forelse ($mailboxes as $mailbox)
            <tr>
                <td>
                    <a href="{{route('mailbox.show',[$mailbox->id])}}">{{$mailbox->username}}</a>
                </td>
                <td>
                    <form action="{{route('mailbox.destroy',[$mailbox->id])}}" method="post">
                        @csrf
                        <input type="hidden" name="_method" value="DELETE">
                        <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
            @empty
            <tr>
                <td>No Mailboxes Found</td>
            </tr>
            @endforelse    
        </tbody>
    </table>
</div>
@endsection

resources/views/mailbox/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <a href="{{route('mailbox.index')}}" class="btn btn-primary btn-sm float-right">Back to Mailboxes</a>
    <a href="{{route('rules.create')}}" class="btn btn-default btn-sm float-right" data-toggle="modal" data-target="#add-rule-modal">Add New Rule</a>
    <h5>{{$mailbox->username}}</h5>
    <div class="py-4"></div>
    <h5>Folders Available</h5>
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th>Mailbox Folder</th>
            </tr>
        </thead>
        <tbody class="table-bordered table-hover">
            @forelse ($mailbox->folders as $folder)
                <tr>
                    <th>{{$folder}}</th>
                </tr>
            @empty
                <th>No Folders Available</th>
            @endforelse
        </tbody>
    </table>
<!-- Button to Open the Modal -->
    <button type="button" class="btn btn-primary btn-sm float-right" data-toggle="modal" data-target="#add-rule-modal">Add New Rule</button>
    <h5>Mailbox Rules</h5>
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th>Rule</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody class="table-bordered table-hover">
            @forelse ($mailbox->Rules as $rules)
                <tr>
                    <th>{{__('default.'.$rules->type)}} {{$rules->folder}} @if($rules->to) to {{$rules->to}} @endif if {{$rules->data}} </th>
                    <th>
                        <div class="btn-group btn-group-sm">
                            <form action="{{route('rules.destroy',[$rules])}}" method="post">
                                @csrf
                                <input type="hidden" name="_method" value="DELETE">
                                <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                            </form>
                        </div>
                    </th>
                </tr>
            @empty
                <th>No Rules Available</th>
            @endforelse
        </tbody>
    </table>
</div>
      <!-- The Modal -->
    <div class="modal" id="add-rule-modal">
        <div class="modal-dialog b-0">
            <div class="modal-content">
                <!-- Modal body -->
                <div class="modal-body">
                        <h4 class="modal-title">Add New Rule</h4>
                <form action="{{route('rules.store')}}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="folder">For Folder</label>
                        <select name="folder" id="folder" class="form-control">
                            @forelse ($mailbox->folders as $folder)
                                <option value="{{$folder}}">{{$folder}}</option>
                            @empty
                                <option selected disabled>No Folders Available</option>
                            @endforelse
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="type">Action</label>
                        <select name="type" id="type" class="form-control" required>
                            <option selected disabled>Select an Action</option>
                            <option value="imap_mail_move">Move to Another Folder</option>
                            <option value="imap_mail_move_read">Move to Another Folder and Mark as Read</option>
                            <option value="imap_delete">Delete Mail</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="to">To Folder </label>
                        <select name="to" id="to" class="form-control">
                            @forelse ($mailbox->folders as $folder)
                                <option value="{{$folder}}">{{$folder}}</option>
                            @empty
                                <option selected disabled>No Folders Available</option>
                            @endforelse
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="data">Email ID / Keyword</label>
                        <input type="text" name="data" id="data" class="form-control">
                        <span class="help-text">Enter Email id, or Any Keyword that has the Following Text</span>
                    </div>
                    <div class="form-group">
                        <input type="hidden" name="mailbox" value="{{$mailbox->id}}">
                        <button type="submit" class="btn btn-success btn-block">Confirm and Save</button>
                    <button type="button" class="btn btn-default btn-block" data-dismiss="modal">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection